### ISSUE TITLE
create-react-native-app my-app Error

### ISSUE THREAD

**Issue by YamgXion** [expo/create-react-native-app#792]
× Something went wrong in downloading and extracting the project files.
What's the reason? How to solve it?

**Comment by brentvatne** [comment]
hello @YamgXion! where are you based out of? can you access npm from your country or do you use another registry?

**Comment by rayandrie** [comment]
Hi, I also got the same error as above. I am in the US and I tried `npx create-react-native-app`, as well as 
`$ npm i -g create-react-native-app`
`$ create-react-native-app my-project`

but both gave me the same error as above.

**Comment by shwetaahuja123** [comment]
Hi @YamgXion, @brentvatne,
I am facing same error.
What is the fix?

**Comment by YamgXion** [comment]
> Hi @YamgXion, @brentvatne,
> I am facing same error.
> What is the fix?

It's my Internet problem, because I used VPN, I need to set up an agent to solve it.
