### ISSUE TITLE
Javascript instead of Typescript

### ISSUE THREAD

**Issue by mivd7** [expo/create-react-native-app#798]
Hello, how can I use create-react-native-app and have it setup with Javascript and not Typescript? So it creates App.js not App.tsx at initialization

**Comment by brentvatne** [comment]
you can rename the file to App.js rather than App.tsx :)

**Comment by jpogah** [comment]
what about the tsconfig.json file? this file is typescript related, should I modify the file after renaming App.tsx to App.js?

**Comment by jpogah** [comment]
> Hello, how can I use create-react-native-app and have it setup with Javascript and not Typescript? So it creates App.js not App.tsx at initialization

This answer is wrong, at least in my case it broke the build. 
<img width="460" alt="Screen Shot 2020-05-08 at 8 56 11 AM" src="https://user-images.githubusercontent.com/16649824/81412671-ce4b5c80-9109-11ea-9d36-5ae474133645.png">

**Comment by jpogah** [comment]
> you can rename the file to App.js rather than App.tsx :)

This answer is wrong. 
<img width="460" alt="Screen Shot 2020-05-08 at 8 56 11 AM" src="https://user-images.githubusercontent.com/16649824/81412859-1cf8f680-910a-11ea-8e40-c82fc1bb305c.png">
It broke my build. Anyone with a better answer on how to initialize with javascript instead of typescript?

**Comment by jpogah** [comment]
> you can rename the file to App.js rather than App.tsx :)

I just want to add that you need to delete tsconfig.json file for everything to work.

**Comment by BeKnowDo** [comment]
I hate that everyone's jumped onto the TS train.

**Comment by VinayakGaikwad101** [comment]
> I hate that everyone's jumped onto the TS train.

Exactly, everyone is jumping on ts/tsx and nextjs like it's the next big thing. C'mon, it's a web development technology, and ts is just for typesafety, no need to force it on everyone
