### ISSUE TITLE
npx create-react-native-app does not work.

### ISSUE THREAD

**Issue by pk936** [expo/create-react-native-app#799]
**Describe the bug**
I tried this command

`npx create-react-native-app`

It says: **Unexpected token {**

**To Reproduce**

1. Go to terminal
2. type npx create-react-native-app
3. Press enter.

I am Using linux.

**Comment by EvanBacon** [comment]
Cannot repro on a linux machine. 

`$ node -v v12.16.2`

Please provide more info.

**Comment by pk936** [comment]
Ok. It's fixed. I had old version of node v8.16.0. Upgraded and solved.
