### ISSUE TITLE
Can't understand how to edit package.json file. Please help

### ISSUE THREAD

**Issue by pragati111** [expo/create-react-native-app#821]
Actually I wanted to make these edits in the package.json file and couldn't get it that how the editing of that file can be done. 
```

"scripts": {
    "start": "node your-script.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

_Originally posted by @hmake98 in https://github.com/expo/create-react-native-app/issues/411#issuecomment-334103854_

**Comment by fson** [comment]
Welcome to the Expo community! 👋 Could you try rephrasing this as a question? It’s often useful to describe the problem in terms of:
- what you’re trying to achieve
- what steps you took (please include any commands you ran, in full, or edits to files)
- what happened
- what you expected to happen instead

That way others will have a better chance to able to help you. Thanks!

**Comment by pragati111** [comment]
@fson  Sir, Actually it was my first time so couldn't mention my query properly and now I have updated the comment that I made some days back. But the thing is that after making these changes(mentioned in the previous comment), I am still facing the problem

**Comment by pragati111** [comment]
@fson Sir, I tried to run npm start and I am getting an error(
![git](https://user-images.githubusercontent.com/56107628/83221119-94aec400-a192-11ea-8966-125535347937.PNG)
)

**Comment by EvanBacon** [comment]
I'm unsure how this relates to the project. Please feel free to reopen when you have a reproducible example.
