### ISSUE TITLE
NPM Start results multiple errors

### ISSUE THREAD

**Issue by lolleri200** [expo/create-react-native-app#826]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactnative@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactnative@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by EvanBacon** [comment]
react-scripts is unrelated to the package. Perhaps you meant https://github.com/facebook/create-react-app/
