### ISSUE TITLE
Typescript templates

### ISSUE THREAD

**Issue by YassineElbouchaibi** [expo/create-react-native-app#835]
Hey, this is a feature request and I would possibly want to work on it as I'm looking for simple stuff to do on my free time.

Basically add the ability to choose between js or ts after selecting a template if that template has ts version.

This could be done in many ways. One of them would be to prepend all ts versions with a keyword (e.g _ts) in expo/examples and hide this in create-react-native-app cli when listing examples. If an example is selected and has a ts version, ask the user if he wants to use it.

Same when using -t (--template), the user would be asked a question about whether he wants to use ts or not

Let me know if you think something like this would be useful

**Comment by EvanBacon** [comment]
In the current version of expo-cli you can convert any file to TypeScript, or create a blank `tsconfig.json` then run expo start to have typescript automatically configured. I think this is the most reasonable method for supporting TS in any project. 
If you'd like to contribute more or improve that feature, I recommend opening a PR on https://github.com/expo/expo-cli/
