### ISSUE TITLE
Broken link to Expo template examples in CLI

### ISSUE THREAD

**Issue by prahaladbelavadi** [expo/create-react-native-app#839]
When creating a new project using create-react-native-app, it asks if you want to create a default blank one or choose one template from the available examples.

When clicking on the link to go to https://github.com/expo/examples​, it goes to https://github.com/expo/examples%E2%80%8B instead. 

When copying the link, it copies "(​https://github.com/expo/examples​" to the clipboard.

Ideal behaviour should be that upon clicking https://github.com/expo/examples link, it should open a tab that leads to https://github.com/expo/examples and when copying the link it should copy https://github.com/expo/examples to the clipboard. 

It likely has something to do with URL encoding;
- https://stackoverflow.com/questions/48868916/angular-add-extra-variable-on-img-at-end-e2808b
- https://www.w3schools.com/tags/ref_urlencode.asp

![image](https://user-images.githubusercontent.com/16673094/87136315-f8abc880-c2b8-11ea-824d-113864df120e.png)
![image](https://user-images.githubusercontent.com/16673094/87136401-19741e00-c2b9-11ea-9fc5-65e67d8aee1b.png)

**Comment by brooksbecton** [comment]
Looks like this got fixed in : a83bcf8d488998abfca007022c79ce8e07eeff0b

**Comment by prahaladbelavadi** [comment]
Awesome! Thanks @brooksbecton @EvanBacon 🚀
