### ISSUE TITLE
i unable to find the right package.json as there is too many of them in my system

### ISSUE THREAD

**Issue by capitalF03** [expo/create-react-native-app#840]
I have the same issue. i try to write a code in package.json file as below
```

"scripts": {
    "start": "node your-script.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```
hope, it will works for you.

_Originally posted by @hmake98 in https://github.com/expo/create-react-native-app/issues/411#issuecomment-334103854_

**Comment by EvanBacon** [comment]
Please reopen after explaining how this is related to the `create-react-native-app` package.
