### ISSUE TITLE
Failed to fetch the list of examples with the following error: HTTPError: Response code 403 (rate limit exceeded)

### ISSUE THREAD

**Issue by Albert-Gao** [expo/create-react-native-app#848]
![image](https://user-images.githubusercontent.com/18282328/90123310-b6dbd980-ddb2-11ea-902d-18944c213b2b.png)

It means this tool is so popular. 👍  Do not know if this is even a bug, just put here to let you guys know :)

**Comment by EvanBacon** [comment]
Thanks Albert. I noticed this has happened once or twice. If anyone can find an alternative API for downloading github projects with a higher rate limit, I'd be happy to help migrate to it.
