### ISSUE TITLE
set app.json splash option no change

### ISSUE THREAD

**Issue by mkRui** [expo/create-react-native-app#850]
**Describe the bug**
default new app option
set app.json splash option 
the app is also the initial startup page not change

**Expected behavior**
It should be based on app.json The configuration of the app shows the startup page of the app

**Desktop (please complete the following information):**
 - iOS 11 simulator

**Smartphone (please complete the following information):**
 -  Android 10 x86 simulator

**Comment by EvanBacon** [comment]
If the app has an ios or android folder, you'll need to run `expo eject` to sync the app.json with the native code.
