### ISSUE TITLE
create react native app typescript

### ISSUE THREAD

**Issue by smashraid** [expo/create-react-native-app#854]
**Describe the bug**
Not able to use import logo from ./assets/logo.png.
Applied a workaround creating index.d.ts with 
declare module '*.jpg'
{
    const content: string;
    export default content;
}

**To Reproduce**
1. npx react-native init bookstore --template react-native-template-typescript
2. Create folder assets with logo.png inside
3. In App.tsx add import { Image} from 'react-native-elements';
4. In App.tsx add import logo from './assets/logo.png';
5. <Image
          source={{ uri: logo }}
          style={{ width: 200, height: 200 }}
        />

**Expected behavior**
Should be imported without compile errors. Not sure if is the same behavior but for create react app for typescript work without problems.

**Screenshots**
![Screenshot_1601594772](https://user-images.githubusercontent.com/2209373/94873086-dd61dc80-0413-11eb-9338-91063d3dbc74.png)
![image](https://user-images.githubusercontent.com/2209373/94873135-fbc7d800-0413-11eb-9d16-d5798168c959.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node: v14.12.0
 - Npm: v6.14.18
 - Expo-Cli: v3.27.12

**Smartphone (please complete the following information):**
 - Device: Emulator 
 - OS: Android
 - Version API 29

**Additional context**
None

**Comment by brooksbecton** [comment]
Using requires is what I normally do. 
https://reactnative.dev/docs/images

Not sure why you have to do the require, but it's what is recommended

**Comment by smashraid** [comment]
I found the problem for typescript you need to use
import { Image } from 'react-native';
const img = Image.resolveAssetSource(logo);

<Image
          source={{ uri: img.uri }}
          style={{ width: 200, height: 200 }}
        />
