### ISSUE TITLE
Brand new create-react-native-app fails to build in Xcode

### ISSUE THREAD

**Issue by jonwinstanley** [expo/create-react-native-app#856]
A new create react native app does not build in Xcode. In trying to debug an issue I have with an existing app, I tried creating a new project and it also does not build.

To reproduce:

npx create-react-native-app basic
> Default new app

cd basic
yarn install

cd ios
pod install

Xcode > Build

Showing All Errors Only
CopySwiftLibs /Users/jon/Library/Developer/Xcode/DerivedData/basic-dshgrcwulgzntuezcfjjqeljqmwb/Build/Products/Debug-iphonesimulator/basic.app (in target 'basic' from project 'basic')
    cd /Users/jon/Dropbox/ReactNative/basic/ios
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
    builtin-swiftStdLibTool --copy --verbose --sign - --scan-executable /Users/jon/Library/Developer/Xcode/DerivedData/basic-dshgrcwulgzntuezcfjjqeljqmwb/Build/Products/Debug-iphonesimulator/basic.app/basic --scan-folder /Users/jon/Library/Developer/Xcode/DerivedData/basic-dshgrcwulgzntuezcfjjqeljqmwb/Build/Products/Debug-iphonesimulator/basic.app/Frameworks --scan-folder /Users/jon/Library/Developer/Xcode/DerivedData/basic-dshgrcwulgzntuezcfjjqeljqmwb/Build/Products/Debug-iphonesimulator/basic.app/PlugIns --platform iphonesimulator --toolchain /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain --destination /Users/jon/Library/Developer/Xcode/DerivedData/basic-dshgrcwulgzntuezcfjjqeljqmwb/Build/Products/Debug-iphonesimulator/basic.app/Frameworks --strip-bitcode --strip-bitcode-tool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip --emit-dependency-info /Users/jon/Library/Developer/Xcode/DerivedData/basic-dshgrcwulgzntuezcfjjqeljqmwb/Build/Intermediates.noindex/basic.build/Debug-iphonesimulator/basic.build/SwiftStdLibToolInputDependencies.dep

error: Build input file cannot be found: '/Users/jon/Library/Developer/Xcode/DerivedData/basic-dshgrcwulgzntuezcfjjqeljqmwb/Build/Products/Debug-iphonesimulator/basic.app/basic' (in target 'basic' from project 'basic')

**Comment by Paul-Taiwo** [comment]
I am facing the same issue too. Every new create react native app doesn't build. Any solution for this?

**Comment by Paul-Taiwo** [comment]
I was able to fix this by removing the quote in `Library Search Path`.

N.B - I used the Legacy Build System
Steps

<img width="1680" alt="Fix" src="https://user-images.githubusercontent.com/33280888/96620869-e3a2f480-12ff-11eb-8d3b-39f78d926b97.png">

**Comment by jonwinstanley** [comment]
I'm pretty much done with React Native now. Anything you try to do which hooks into native code is another possibility of breaking the build. Haptic feedback, in-app purchases, gestures etc etc.

**Comment by raajnadar** [comment]
This only happens to me when I used managed template and after that I eject it. When I use default template it is working properly.

**Comment by EvanBacon** [comment]
Seems like this was related to the default react-native template, which has since been fixed (also which `expo eject` used to use, but doesn't anymore).
