### ISSUE TITLE
Broken link to RN tutorial docs 

### ISSUE THREAD

**Issue by kartikcho** [expo/create-react-native-app#857]
Current `readme` has a [broken link](https://reactnative.dev/docs/tutorial.html) to the React Native docs which could be confusing for a lot of new folks. 

![image](https://user-images.githubusercontent.com/48270786/97794899-c63a2880-1c25-11eb-816a-c761acdd7b0b.png)

**Comment by darshkpatel** [comment]
This might be related to the RN Docs upgrade, I'll check with the team about the best course of action 
ie. To update links ( I'm afraid there might be many broken links ) or to add redirects for such pages on the website

**Comment by slorber** [comment]
fixed on RN website!
