### ISSUE TITLE
template list not available 

### ISSUE THREAD

**Issue by ClementBolin** [expo/create-react-native-app#861]
**Describe the bug**
I tryed to init react-native app but when I should normally have had the list of templates available, I got an error telling me that it was impossible to retrieve this list.

**To Reproduce**
start ```npx create-react-native-app```

**Screenshots**
```bash
Failed to fetch the list of examples with the following error:
HTTPError: Response code 403 (rate limit exceeded)
    at PromisableRequest.<anonymous> (/Users/clementbolin/.npm/_npx/e8d9921bba236b1e/node_modules/create-react-native-app/build/index.js:2:405547)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  code: undefined,
  timings: {
    start: 1605978607015,
    socket: 1605978607017,
    lookup: 1605978607054,
    connect: 1605978607090,
    secureConnect: 1605978607136,
    upload: 1605978607137,
    response: 1605978607183,
    end: 1605978607188,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 37,
      tcp: 36,
      tls: 46,
      request: 1,
      firstByte: 46,
      download: 5,
      total: 173
    }
  }
}
```
**Desktop (please complete the following information):**
 - OS: macOs big sur
 - Version v11.0.1

**Comment by flexbox** [comment]
Hey @ClementBolin 

I tried on 
- OS: macOs big sur
- Version v11.0.1


and it's working 

![image](https://user-images.githubusercontent.com/360936/100890532-a615b780-34b8-11eb-834c-5dc4a0709c78.png)

Can you check the output of `npx react-native doctor` to detect if you have setup errors?

**Comment by ClementBolin** [comment]
Heu @flexbox

I tried  ```npx react-native doctor``` and I had 0 errors and 0 warnings.
I tried again to create a react-native application with ```npx create-react-native-app``` and this time I didn't get the error I posted.

**Comment by flexbox** [comment]
Maybe it was a network problem, I think you can close the issue 😉
