### ISSUE TITLE
No qr code but a strange blue star

### ISSUE THREAD

**Issue by Venon282** [expo/create-react-native-app#867]
**Describe the bug**
A have no qr code when i start npm on the window cmd

**To Reproduce**
![image](https://user-images.githubusercontent.com/58562700/101218074-b5e0f780-3682-11eb-97a0-5fd9cd3d99ab.png)

have you an idea for this problem ? 

thanks ))

**Comment by EvanBacon** [comment]
Looks like you're running the app with `react-native-community/cli`. Run `expo start` to get the QR code.
