### ISSUE TITLE
I tried to install npm install -g firbase-tools but not installed

### ISSUE THREAD

**Issue by moiza261** [expo/create-react-native-app#869]
**Describe the bug**

When i install firbase hosting and open cmd and type npm install -g firbase-tools but make an error and firbase not install

**Comment by j0nas** [comment]
@moiza261 Fir**e**base. :slightly_smiling_face:  

`npm install -g firebase-tools`

**Comment by EvanBacon** [comment]
Please reopen after explaining how this is related to the `create-react-native-app` package.
