### ISSUE TITLE
Uncaught Error: java.net.SocketTimeoutException: failed to connect to /192.168.0.102 (port 19000) from / 192.168.0.100 (port 42950) after 10000ms

### ISSUE THREAD

**Issue by 86-umang** [expo/create-react-native-app#876]
My react native project run on android emulator  
but whenever i try to connect my project with my android device then above error occur.
**note**: my mobile and laptop are connected with the same wifi connection.
Please help me with this issue.

**Uncaught Error: java.net.SocketTimeoutException: failed to connect to /192.168.0.102 (port 19000) from / 192.168.0.100 (port 42950) after 10000ms**

**Comment by William-2020-03-03** [comment]
I met the same issue. But I have no idea. I also want a solution.

**Comment by 86-umang** [comment]
> I met the same issue. But I have no idea. I also want a solution.

I solved it.

**Follow the steps.**

**1.)** Turn on **USB Tethering** & **USB Debugging** Mode in your mobile.
**2.)** Connect your mobile to your laptop through USB.
**3.)** Now just **change the ip** address **(run "ipconfig" in cmd)** from your **backend** code.

Above solution is worked for me.

Try it. It will work.

**let me know if some error occur and also Write a comment if the solution works.**

**Comment by momnaimran** [comment]
> > I met the same issue. But I have no idea. I also want a solution.
> 
> I solved it.
> 
> **Follow the steps.**
> 
> **1.)** Turn on **USB Tethering** & **USB Debugging** Mode in your mobile.
> **2.)** Connect your mobile to your laptop through USB.
> **3.)** Now just **change the ip** address **(run "ipconfig" in cmd)** from your **backend** code.
> 
> Above solution is worked for me.
> 
> Try it. It will work.
> 
> **let me know if some error occur and also Write a comment if the solution works.**

omg this finally worked for me. I have been trying for 2 days and i was so freakin frustrated. Thank you so much for the solution

**Comment by 86-umang** [comment]
> > > I met the same issue. But I have no idea. I also want a solution.
> > 
> > 
> > I solved it.
> > **Follow the steps.**
> > **1.)** Turn on **USB Tethering** & **USB Debugging** Mode in your mobile.
> > **2.)** Connect your mobile to your laptop through USB.
> > **3.)** Now just **change the ip** address **(run "ipconfig" in cmd)** from your **backend** code.
> > Above solution is worked for me.
> > Try it. It will work.
> > **let me know if some error occur and also Write a comment if the solution works.**
> 
> omg this finally worked for me. I have been trying for 2 days and i was so freakin frustrated. Thank you so much for the solution

You are welcome!
I wasted one week on this solution.

**Comment by EvanBacon** [comment]
This seems to be more closely related to the Metro bundler and react-native runtime, not to the bootstrapping script (this repo). https://github.com/react-native-community/cli

**Comment by 86-umang** [comment]
> > > I met the same issue. But I have no idea. I also want a solution.
> > 
> > 
> > I solved it.
> > **Follow the steps.**
> > **1.)** Turn on **USB Tethering** & **USB Debugging** Mode in your mobile.
> > **2.)** Connect your mobile to your laptop through USB.
> > **3.)** Now just **change the ip** address **(run "ipconfig" in cmd)** from your **backend** code.
> > Above solution is worked for me.
> > Try it. It will work.
> > **let me know if some error occur and also Write a comment if the solution works.**
> 
> omg this finally worked for me. I have been trying for 2 days and i was so freakin frustrated. Thank you so much for the solution


You are welcome...

**Comment by 0303vikas** [comment]
I just needed to change my wifi settings from public to private in Windows. After changing this, it worked for me.

**Comment by maheshsompalli** [comment]
> I just needed to change my wifi settings from public to private in Windows. After changing this, it worked for me.
