### ISSUE TITLE
When enabling debug mode, the crash application 

### ISSUE THREAD

**Issue by cleversonffaria** [expo/create-react-native-app#879]
**Describe the bug**
When starting a project with create-react-native-app and enabling debug mode, the application hangs without an error log. 
Some solution to the problem that has occurred since 1 week here?

This happens only on Android.
In IOS it works normally.

![image](https://user-images.githubusercontent.com/34727083/117487235-301eec00-af41-11eb-9873-2376aaab37c2.png)

**Comment by tuliosciotta** [comment]
Same issue here.

**Comment by EvanBacon** [comment]
This is because remote JS debugging doesn't support JSI, the default template uses JSI (the latest React Native architecture). Please use flipper for debugging or uninstall reanimated and any other modules that may be using the latest React Native features.
