### ISSUE TITLE
i have a probleme anyone can help me

### ISSUE THREAD

**Issue by Moktadahl** [expo/create-react-native-app#893]
Error: Cannot find module '/home/runner/Pro-Moderation/your-script.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-moderation-bot@2.0.0 start: `node your-script.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord-moderation-bot@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-09-05T07_52_30_724Z-debug.log
exit status 1


**Comment by EvanBacon** [comment]
Please use stackoverflow.com for general JavaScript questions.
